name: Build, test, publish

on:
  push:
    tags: 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Nim
      # You may pin to the exact commit or the version.
      # uses: iffy/install-nim@7dd1812db4916d00b984d1c43339346a76e05487
      uses: iffy/install-nim@v4.1.3
      #with:
        # 
        #version: # optional, default is stable
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: docker login
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: gstein17/roboscapeonlineapiserver:latest
